services:
  app:
    image: us-central1-docker.pkg.dev/stock-price-alert-gcp/stock-apps/app:latest
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - redis

  worker:
    image: us-central1-docker.pkg.dev/stock-price-alert-gcp/stock-apps/app:latest
    command: celery -A tasks worker --loglevel=info
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
