services:
  app:
    image: us-central1-docker.pkg.dev/stock-price-alert-gcp/stock-apps/app:latest
    ports:
      - "8000:8000"
    environment:
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    image: us-central1-docker.pkg.dev/stock-price-alert-gcp/stock-apps/app:latest
    command: celery -A tasks worker --loglevel=info
    environment:
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  
  ui:
    image: us-central1-docker.pkg.dev/stock-price-alert-gcp/stock-apps/app:latest
    command: streamlit run frontend.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - app
